import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :kart_vids, KartVidsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure video storage location
config :kart_vids,
  videos_bucket_name: System.fetch_env!("KART_VIDS_BUCKET_NAME_PROD")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
